# # Form implementation generated from reading ui file 'C:\Users\Lenovo\Desktop\musicplayer.ui'
# #
# # Created by: PyQt6 UI code generator 6.11.0
# #
# # WARNING: Any manual changes made to this file will be lost when pyuic6 is
# # run again.  Do not edit this file unless you know what you are doing.


# from PyQt6 import QtCore, QtGui, QtWidgets
# from PyQt6.QtMultimedia import *
# import pathlib 
# from pathlib import Path


# class Ui_Form(object):
#     def setupUi(self, Form):
#         Form.setObjectName("Form")
#         Form.resize(982, 366)
#         self.listWidget = QtWidgets.QListWidget(parent=Form)
#         self.listWidget.setObjectName("listWidget")
#         self.WidgetItems = QtWidgets.QListWidgetItem()
#         Path(__file__).parent
#         index = Path.cwd()/Path.glob(self, pattern="*.mp3")
#         print(index)
#         self.listWidget.addItem(index)
#         self.WidgetItems.currentIndex()


#         self.play_audio = QtWidgets.QPushButton(parent=Form)
#         self.play_audio.setObjectName("play_audio")
#         self.set_as_background_music = QtWidgets.QPushButton(parent=Form)
#         self.set_as_background_music.setObjectName("set_as_background_music")
#         self.set_folder = QtWidgets.QPushButton(parent=Form)
#         self.set_folder.setObjectName("set_folder")
#         self.stop_audio = QtWidgets.QPushButton(parent=Form)
#         self.stop_audio.setObjectName("stop_audio")
#         self.adjust_volume = QtWidgets.QLabel(parent=Form)
#         self.adjust_volume.setObjectName("adjust_volume")

#         self.retranslateUi(Form)
#         QtCore.QMetaObject.connectSlotsByName(Form)
#         top_buttons = QtWidgets.QHBoxLayout()
#         top_buttons.addWidget(self.play_audio)
#         top_buttons.addWidget(self.stop_audio)

#         right_col = QtWidgets.QVBoxLayout()
#         right_col.addLayout(top_buttons)
#         right_col.addWidget(self.set_as_background_music)
#         right_col.addWidget(self.set_folder)
#         right_col.addWidget(self.adjust_volume)
#         right_col.addStretch()

#         main_layout = QtWidgets.QHBoxLayout(Form)
#         main_layout.addWidget(self.listWidget, 3)   # list gets 3 parts of the width
#         main_layout.addLayout(right_col, 2) 


#         "this code here runs the audio player"
#         self.AudioPlayer = QAudioOutput(Form)
#         self.AudioPlayer.setVolume(0.5)

#         self.Player = QMediaPlayer(Form)
#         self.Player.setAudioOutput(self.AudioPlayer)

#         # self.open_file_action = self.play_audio
#         # self.open_file_action.triggered.connect(self.open_file)
#         # self.setAcceptDrops(True)

#     def retranslateUi(self, Form):
#         _translate = QtCore.QCoreApplication.translate
#         Form.setWindowTitle(_translate("Form", "Form"))
#         self.play_audio.setText(_translate("Form", "Play"))
#         self.set_as_background_music.setText(_translate("Form", "Set as background music"))
#         self.set_folder.setText(_translate("Form", "Select audio folder"))
#         self.stop_audio.setText(_translate("Form", "Stop"))
#         self.adjust_volume.setText(_translate("Form", "Volume Settings"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Form = QtWidgets.QWidget()
#     ui = Ui_Form()
#     ui.setupUi(Form)
#     Form.show()
#     sys.exit(app.exec())


"""Music sample · PY"""
import sys
from pathlib import Path
 
from PyQt6.QtCore import Qt, QUrl
from PyQt6.QtMultimedia import QAudioOutput, QMediaPlayer
from PyQt6.QtWidgets import (
    QApplication, QFileDialog, QListWidget, QListWidgetItem,
    QMainWindow, QPushButton, QStackedWidget, QVBoxLayout, QWidget,
)
 
MUSIC_DIR = Path(__file__).parent / "music"   # folder next to this script
AUDIO_PATTERNS = ("*.mp3", "*.wav", "*.ogg")
 
 
class MenuPage(QWidget):
    """Page 0: main menu."""
    def __init__(self):
        super().__init__()
        self.to_library = QPushButton("Go to library")
        layout = QVBoxLayout(self)
        layout.addWidget(self.to_library)
 
 
class LibraryPage(QWidget):
    """Page 1: lists audio files and lets the user pick one."""
    def __init__(self):
        super().__init__()
        self.list_widget = QListWidget()
        self.browse_btn = QPushButton("Browse...")
        self.assign_btn = QPushButton("Use selected as menu music")
        self.back_btn = QPushButton("Back")
 
        layout = QVBoxLayout(self)
        for w in (self.list_widget, self.browse_btn, self.assign_btn, self.back_btn):
            layout.addWidget(w)
 
        self.refresh()
 
    def refresh(self):
        self.list_widget.clear()               # avoids duplicates
        if not MUSIC_DIR.exists():
            return
        for pattern in AUDIO_PATTERNS:         # glob takes one pattern at a time
            for path in MUSIC_DIR.glob(pattern):
                item = QListWidgetItem(path.name)                 # shown text
                item.setData(Qt.ItemDataRole.UserRole, str(path)) # hidden full path
                self.list_widget.addItem(item)
 
 
class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
 
        # --- audio ---
        self.player = QMediaPlayer()
        self.audio_out = QAudioOutput()
        self.player.setAudioOutput(self.audio_out)   # player needs an output
        self.audio_out.setVolume(0.5)
 
        # page index -> track path (None = no music assigned, keep current)
        self.page_tracks = {0: None, 1: None}
        self.current_track = None
 
        # --- pages ---
        self.menu_page = MenuPage()
        self.library_page = LibraryPage()
 
        self.stack = QStackedWidget()
        self.stack.addWidget(self.menu_page)      # index 0
        self.stack.addWidget(self.library_page)   # index 1
        self.setCentralWidget(self.stack)
 
        # --- connections ---
        self.stack.currentChanged.connect(self.on_page_changed)
        self.menu_page.to_library.clicked.connect(lambda: self.stack.setCurrentIndex(1))
        self.library_page.back_btn.clicked.connect(lambda: self.stack.setCurrentIndex(0))
        self.library_page.browse_btn.clicked.connect(self.browse_file)
        self.library_page.assign_btn.clicked.connect(self.assign_selected)
 
    # --- audio logic ---
    def on_page_changed(self, index):
        track = self.page_tracks.get(index)
        if track is None or track == self.current_track:
            return                                # nothing assigned, or same song: continue
        self.play_track(track)
 
    def play_track(self, path):
        self.player.setSource(QUrl.fromLocalFile(str(path)))
        self.player.play()
        self.current_track = path
 
    def set_menu_track(self, path):
        self.page_tracks[0] = path
        if self.stack.currentIndex() == 0:
            self.on_page_changed(0)
 
    # --- file selection ---
    def browse_file(self):
        path, _ = QFileDialog.getOpenFileName(
            self, "Choose audio", str(MUSIC_DIR),
            "Audio files (*.mp3 *.wav *.ogg)",
        )
        if path:                                  # empty string if cancelled
            self.set_menu_track(path)
 
    def assign_selected(self):
        item = self.library_page.list_widget.currentItem()
        if item:
            self.set_menu_track(item.data(Qt.ItemDataRole.UserRole))
 
 
if __name__ == "__main__":
    app = QApplication(sys.argv)
    win = MainWindow()
    win.show()
    sys.exit(app.exec())
 
